blueprint:
  name: Morning routine
  description: Automate a dehumidifier using humidity, presence, time, and smart plug monitoring.
  domain: automation
  input:
    toothbrush:
      name: Duration of tooth brushing
      description: Sensor measuring the duration of tooth brushing.
      selector:
        entity:
          domain: sensor
    person:
      name: Person to check presence for
      description: Sensor to monitor person presence.
      selector:
        entity:
          domain: person
    temperature_sensor:
      name: Temperature
      description: Sensor to monitor temperature.
      selector:
        entity:
          domain: sensor
    maximum_temperature:
      name: Maximum Temperature
      description: Temperature above which the curtains should not open.
      default: 28
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "°C"
    start_time:
      name: Start Time
      description: Time of day to start automation checks.
      default: "06:45:00"
      selector:
        time: {}
    end_time:
      name: End Time
      description: Time of day to stop automation checks.
      default: "14:00:00"
      selector:
        time: {}
    curtains:
      name: Curtains
      description: Curtains to open.
      selector:
        entity:
          domain: cover

triggers:
  - trigger: numeric_state
    entity_id:
      - !input toothbrush
    above: 5
  - trigger: time
    at: "09:00:00"
    id: morning

conditions:
  - condition: time
    after: !input start_time
    before: !input end_time
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: zone
            entity_id: !input person
            zone: zone.home
          - condition: not
            conditions:
              - condition: trigger
                id:
                  - morning
            alias: "If not triggered by morning"
      - condition: and
        conditions:
          - condition: not
            conditions:
              - condition: zone
                entity_id: !input person
                zone: zone.home
            alias: If not home
          - condition: trigger
            id:
              - morning
  - condition: numeric_state
    entity_id: !input temperature_sensor
    domain: sensor
    below: !input maximum_temperature

actions:
  - data: {}
    target:
      entity_id: !input curtains
    action: cover.open_cover
